### ISSUE TITLE
Commandbox install not working

### ISSUE THREAD

**Issue by phipps73** [coldfumonkeh/googleindex#1]
Just tried running `box install googleindex` and get the following error:

> Error cloning github repository                                                                                                                                  
> org.eclipse.jgit.api.errors.RefNotFoundException: Ref v1.0.0 cannot be resolved

**Comment by coldfumonkeh** [comment]
Hey @phipps73. Thanks for the heads up. The tag hadn't made it to the repository. This is now fixed and works. Apologies for the inconvenience
