### ISSUE TITLE
Please define testbox as devdependency only

### ISSUE THREAD

**Issue by eppinger** [coldfumonkeh/googleindex#3]
`  
  "dependencies":{
       "testbox":"^2.5.0+107"
    },
`
If   i install  per box install googleindex for production testbox is not needed.

Thanks

**Comment by coldfumonkeh** [comment]
Thanks @eppinger. I should have made that a dev dependency. I'll update `box.json` to reflect that

**Comment by eppinger** [comment]
Thanks ! @coldfumonkeh 

and thanks for this module too

**Comment by coldfumonkeh** [comment]
More than welcome sir!
