### ISSUE TITLE
getAccessToken failing with invalid_grant error on production server

### ISSUE THREAD

**Issue by phipps73** [coldfumonkeh/googleindex#8]
I have implemented GoogleIndex and it appears to work on my local dev machine. However, uploading the code onto an EC2 running Ubuntu 18 and Lucee 5.x (latest) I am unable to even get the access token. The error is:

invalid_grant
Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim.

The same credentials are being used on both local dev site and server. The server time is correctly set and runs in UTC. Would the java version have any impact or do I need to consider something else? This is the code that is failing:

```
public struct function getAccessToken(){
        var JWTPayload = buildJWT();
        cfhttp( url=getTokenEndpoint(), method='POST', result='result' ){
            cfhttpparam( type='formfield', name='grant_type', value='urn:ietf:params:oauth:grant-type:jwt-bearer' );
            cfhttpparam( type='formfield', name='assertion', value=JWTPayload );
        }
        var stuResponse = deserializeJSON( result[ 'fileContent' ] );
        setAccessToken( stuResponse.access_token ?: '' );
        return stuResponse;
   }
```

Locally I see an access token returned. One the production server the 'invalid_grant' error.

Any ideas?

**Comment by coldfumonkeh** [comment]
Hey @phipps73 

The `invalid_grant` error normally comes from one of the following (quotes from the [RFC 6749 OAuth 2.0](https://tools.ietf.org/html/rfc6749#section-5.2) spec):

> The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.

https://blog.timekit.io/google-oauth-invalid-grant-nightmare-and-how-to-fix-it-9f4efaf1da35

**Comment by phipps73** [comment]
Thanks for the info. I have read through that blog post and the issue that I have is that running locally the code is working. It only fails when uploaded to the production server.  I have checked that the credentials.json file is loading correctly and that the private key is being properly extracted. The getAccessToken method returns a token on my local dev server (commandbox server instance) - uploading to the production server results in the invalid_grant error.  I have reduced the code to the bare minimum so my controller is doing this:
```
rc.objGoogleIndex = new googleindex.GoogleIndex( expandPath( './assets/gindex/credentials.json' ) );
rc.accessToken = rc.objGoogleIndex.getAccessToken();
dump(rc.accessToken);
```
local server (commandbox): 
```
access_token: gya29.c....
expires_in: 3599
token_type: Bearer
```
on prod server (ubuntu 18, same lucee version as local dev) date/time on server correct in UTC format:
```
invalid_grant
Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim.
```
Would google have blocked the live domain or is there some callback that google makes to validate the calling domain - the site is restricted access to my office IP via Cloudfront WAF.

**Comment by phipps73** [comment]
@coldfumonkeh have just tried on a different server (another AWS EC2 instance) running Lucee 5.3.9.160 with Apache Tomcat/9.0.31 and 11.0.6 (AdoptOpenJDK) 64bit and I am seeing the same invalid_grant error. The same code is working on the local commandbox dev server. Date on EC2 matches current UTC date/time. Could it be the java version?

**Comment by phipps73** [comment]
I have just upgraded the jre on one of the EC2 instances to 17.0.4.1 (Eclipse Adoptium) 64bit and I am still seeing the same error. I cannot understand why the code works on my local dev server but not on EC2.

**Comment by phipps73** [comment]
@vitopellicano Sadly not. I am running the application on my local dev machine to handle the indexing as it works. As soon as I upload the code to the production server it throws the errors.
@coldfumonkeh happy to pay for your time to fix/investigate this issue.

**Comment by coldfumonkeh** [comment]
Sorry for the delay in response. I'll take a look and see if I can figure out what's happening here

**Comment by phipps73** [comment]
@coldfumonkeh No probs. I am using my local dev version to index the pages I need. If you want to dm me (via cfml slack @davla). I am happy to sponsor to fix the issue.

**Comment by coldfumonkeh** [comment]
@phipps73 Can you try and change the `buildJWT()` method on the production server component to use the following to generate the payload? I am wondering if there is something funky going on with the dates that might be causing an issue on that server.

```
/**
* Builds the JWT needed for access token requests
*/
private string function buildJWT(){
    var currDateTime  = now();
    var credJSON      = getCredentialsJSON();
    var payload       = {
        'iss'  : credJSON[ 'client_email' ],
        'scope': 'https://www.googleapis.com/auth/indexing',
        'aud'  : getTokenEndpoint(),
        'exp'  : generateEpochTime( dateAdd( 'h', 1, currDateTime ) ),
        'iat'  : generateEpochTime( currDateTime )
    };
    return encode( payload = payload );
}
```

**Comment by phipps73** [comment]
@coldfumonkeh That appears to have fixed the problem!!

**Comment by coldfumonkeh** [comment]
I haven't included the JWT library as it uses a different signing algorithm, but I have updated to version 1.1.0 which includes the above fix for the JWT.
